### ISSUE TITLE
Crashes with the Kotlin Mod on Forge

### ISSUE THREAD

**Issue by ClearLite** [zomb-676/HologramPanel#8]
### Mod Loader

- [x] Forge

### Minecraft Version

1.20.1

### ModLoader Version

Forge 47.4.0

### The latest.log file

https://pastebin.com/Wg2PAUR2

### Issue description

For Forge 1.20.1, I made a brand new modpack on Curseforge and I only added 2 mods:

- HologramPanel (latest version)
- Kotlin for Forge (latest version)

And it crashes. But when Kotlin is disabled, it works. Kotlin is a dependency mod for other mods and it has almost 100 million downloads, so hopefully you make the mod compatible with Kotlin so it can work in my modpack 🙏.

**Comment by zomb-676** [comment]
Have you tried this version https://modrinth.com/mod/hologram-panel/version/1.20.1-forge-1.0.3 ?
Curseforge takes about 12 hours to review, you may missing the latest version
I see you use the 1.0.1 version, this has been fixed since 1.0.2

**Comment by ClearLite** [comment]
It still crashed :/

I went to Modrinth and made this modpack:

![Image](https://github.com/user-attachments/assets/2d797187-343f-47a7-bc96-637475222ece)

Here's the logs: https://pastebin.com/zzR9N12f

Also thanks for the quick response I didn't expect you to reply so fast 💀.

**Comment by ClearLite** [comment]
Actually I just tested the modpack with Kotlin disabled in Modrinth and ONLY Hologram Panel enabled and it crashed ( https://pastebin.com/PibA9Fhd ) I should of said this in the previous response my bad 💀

**Comment by zomb-676** [comment]
![Image](https://github.com/user-attachments/assets/79651a0d-adc0-4174-bedc-cd504f5df63e)
There is something wrong with the publish script. I re-upload manually.
Re-download from Modrinth and try it again, please.
https://modrinth.com/mod/hologram-panel/version/1.21.1-forge-1.0.3

**Comment by crafting-Aaron** [comment]
Here to say 1.0.3 from Modrinth did work! Now to just wait for it to upload on Curse Forge. My log also involved kotlin issues which mentioned Better Tridents specifically but seems to have gotten fixed overall. 

Unfortunately there seems to be a bug with the config file now...

**Comment by ClearLite** [comment]
> There is something wrong with the publish script. I re-upload manually.
Re-download from Modrinth and try it again, please.
https://modrinth.com/mod/hologram-panel/version/1.21.1-forge-1.0.3

It now works for me, even with Kotlin 👍.

**Comment by zomb-676** [comment]
> Unfortunately there seems to be a bug with the config file now...

Describe it in detail, please, or just open another issue
